### ISSUE TITLE
Objective-Cの一部のクラスをSwiftのクラスにコンバートしてほしい

### ISSUE THREAD

**Issue by akuraru** [yahoojapan/objc2swift#10]
NSIntegerはIntにコンバートされるが、NSStringなどはコンバートされないものがある。
発見したものは以下のもの。

* NSString -> String
* NSMutableArray -> [AnyObject]
* NSMutableDictionary -> [AnyObject: AnyObject]

**Comment by taketo1024** [comment]
ご報告ありがとうございます、対応します。
