### ISSUE TITLE
Add gradle wrapper

### ISSUE THREAD

**Issue by shiraji** [yahoojapan/objc2swift#4]
In README, it says

```
$ git clone https://github.com/yahoojapan/objc2swift.git
$ cd objc2swift
$ gradle jar
```

This project assumes developers to install gradle. Most iOS developers do not install gradle since it is groovy base tool. Could you provide gradle wrapper? And change CLI command to

```
$ git clone https://github.com/yahoojapan/objc2swift.git
$ cd objc2swift
$ ./gradlew jar
```

Or could you provide instruction on how to install gradle, which version of gradle require for this project, etc.

Thanks in advance.

**Comment by taketo1024** [comment]
Thanks, I'll look into it.

**Comment by taketo1024** [comment]
I've added gradle wrapper files in this branch: 
https://github.com/yahoojapan/objc2swift/tree/feature/add-gradlew

Seems like it works fine on my environment.

**Comment by shiraji** [comment]
Yes, now it works. Thanks.

**Comment by taketo1024** [comment]
merged into develop. thank you!
